{# Check if timeout command exist exit #}
TIMEOUT = $(shell command -v timeout 2> /dev/null)
ifdef TIMEOUT
	TIMEOUT = timeout -k 5s 10s
endif

SRC = $(wildcard *.{{ext}})
.PHONY: exe
exe: $(SRC:%.{{ext}}=%.exe)

pEXE = $(wildcard *.exe)
.PHONY: run
run: $(addprefix run_, $(basename $(pEXE)))

%.exe: %.{{ext}}
{%-if ext == "F90" %}
	-$(FC) $(FFLAGS) $< -o $@
{%-elif ext == "cpp"%}
	-$(CXX) $(CXXFLAGS) $< -o $@
{%endif%}

run_%: %.exe
	-$(TIMEOUT) ./$<

.PHONY: clean
clean:
	rm -f -- $(pEXE) 

