{# Check if timeout command exist exit #}

TIMEOUT = $(shell command -v timeout 2> /dev/null)
OVO_TIMEOUT ?= 10s
ifdef TIMEOUT
	TIMEOUT = timeout -k 5s $(OVO_TIMEOUT)
endif

SRC = $(wildcard *.{{ext}})
.PHONY: exe
exe: $(SRC:%.{{ext}}=%.exe)

pEXE = $(wildcard *.exe)
.PHONY: run
run: $(addprefix run_, $(basename $(pEXE)))

%.exe: %.{{ext}}
{%-if ext == "F90" %}
	-$(TIMEOUT) $(FC) $(FFLAGS) $(CURDIR)/$< -o $(CURDIR)/$@
{%-elif ext == "cpp"%}
	-$(TIMEOUT) $(CXX) $(CXXFLAGS) $(CURDIR)/$< -o $(CURDIR)/$@
{%endif%}

run_%: %.exe
	-$(TIMEOUT) $(CURDIR)/$<

.PHONY: clean
clean:
	rm -f -- $(pEXE) 

