{# Check if timeout command exist exit #}
TIMEOUT = $(shell command -v timeout 2> /dev/null)
ifdef TIMEOUT
	TIMEOUT = timeout -k 5s 10s
endif

SRC = $(wildcard *.{{ext}})
EXE = $(SRC:%.{{ext}}=%.exe)

.PHONY: exe
exe: $(EXE)

pEXE = $(wildcard *.exe)
RUN = $(addprefix run_, $(basename $(pEXE)))

{% for name in ("loop","long") %}
SRC_NO_{{name|upper}} = $(filter-out $(wildcard *{{name}}*.{{ext}}), $(SRC))
EXE_NO_{{name|upper}} = $(SRC_NO_{{name|upper}}:%.{{ext}}=%.exe)

.PHONY: exe_no_{{name}}
exe_no_{{name}}: $(EXE_NO_{{name|upper}})
{% endfor %}

.PHONY: exe_no_long_no_loop
exe_no_long_no_loop: $(filter $(EXE_NO_LONG), $(EXE_NO_LOOP)) {# Interception #}

%.exe: %.{{ext}}
{%-if ext == "F90" %}
	-$(FC) $(FFLAGS) $< -o $@
{%-elif ext == "cpp"%}
	-$(CXX) $(CXXFLAGS) $< -o $@
{%endif%}

.PHONY: run
run: $(RUN)
run_%: %.exe
	-$(TIMEOUT) ./$<

.PHONY: clean
clean:
	rm -f -- $(pEXE) 

